import numpy as np

print(np.zeros((4, 3)))
print(np.arange(5))
print(np.char.add(["hello", "hi"], ["abc", "xyz"]))
print(np.char.multiply("Hello", 3))
print(np.char.center("Hello", 20))
print(np.char.center("Hello", 20, fillchar="-"))
print(np.char.capitalize("hello world"))
print(np.char.title("hello world"))
print(np.char.lower(["HELLO", "WORLD"]))
print(np.char.lower("HELLO"))
print(np.char.upper(["hello", "world"]))
print(np.char.upper("hello"))
print(np.char.split("a b c d e"))
print(np.char.splitlines("a b c\nd e"))
print(np.char.strip(["nina", "admin", "anaita"], "a"))
print(np.char.join([":", "-"], ["dmy", "ymd"]))
print(np.char.replace("he is a good dancer", "is", "was"))
