print(True or False)
print(True or True)
print(True or False or False)
print(False or False)
print(not False)
print(not True)
print(not (False or False))
print(not False or False)
print(False and True)
print(False and False)
print(True and True)
print(True and False or True)
